/**
 * validate-email.ts
 *
 * Two-layer email validation:
 *  Layer 2 — Disposable / throwaway email domain blocklist
 *  Layer 3 — MX record DNS lookup (domain can actually receive mail)
 *
 * Both run server-side only (uses Node.js `dns` module).
 */

import { promises as dns } from 'dns';

// ─── Layer 2: Disposable / Temporary Email Domain Blocklist ─────────────────
// Common throwaway / burner / spam-trap email services.
// Add more as needed — keep alphabetically sorted for easy maintenance.
const DISPOSABLE_DOMAINS = new Set([
  '0-mail.com',
  '0815.ru',
  '10mail.org',
  '10minutemail.com',
  '10minutemail.net',
  '20minutemail.com',
  'altmails.com',
  'anonymail.dk',
  'binkmail.com',
  'blowmail.com',
  'bobmail.info',
  'bsn.cloudns.cx',
  'bugmenot.com',
  'burnermail.io',
  'byom.de',
  'chacuo.net',
  'clandest.in',
  'cool.fr.nf',
  'correo.blogos.net',
  'cosmorph.com',
  'courriel.fr.nf',
  'crapmail.org',
  'curryworld.de',
  'cyber-phone.eu',
  'dayrep.com',
  'deadaddress.com',
  'devnullmail.com',
  'discardmail.com',
  'discardmail.de',
  'discard.email',
  'disposableaddress.com',
  'disposableemailaddresses.com',
  'disposableinbox.com',
  'disposablemail.net',
  'disposablemailhosting.com',
  'dodgit.com',
  'donemail.ru',
  'dontreg.com',
  'dontsendmespam.de',
  'drdrb.com',
  'dump-email.info',
  'dumpandfuck.com',
  'dumpmail.de',
  'dumpyemail.com',
  'e4ward.com',
  'email60.com',
  'emaildienst.de',
  'emailias.com',
  'emailinfive.com',
  'emailisvalid.com',
  'emailmiser.com',
  'emailsensei.com',
  'emailtemporanea.com',
  'emailtemporanea.net',
  'emailtemporario.com.br',
  'emailthe.net',
  'emailtmp.com',
  'emailwarden.com',
  'emailx.at.hm',
  'emailxfer.com',
  'emz.net',
  'ephemail.net',
  'etranquil.com',
  'etranquil.net',
  'etranquil.org',
  'evopo.com',
  'example.com',
  'explodemail.com',
  'eyepaste.com',
  'fakeinbox.com',
  'fakeinformation.com',
  'fakemail.net',
  'fastacura.com',
  'fastchevy.com',
  'fastchrysler.com',
  'fastkawasaki.com',
  'fastmazda.com',
  'fastmitsubishi.com',
  'fastnissan.com',
  'fastsubaru.com',
  'fastsuzuki.com',
  'fasttoyota.com',
  'fastyamaha.com',
  'filzmail.com',
  'fivemail.de',
  'fizmail.com',
  'fleckens.hu',
  'frapmail.com',
  'freemail.ms',
  'freundin.ru',
  'front14.org',
  'fuckingduh.com',
  'fudgerub.com',
  'fylr.it',
  'garliclife.com',
  'get1mail.com',
  'getonemail.com',
  'getonemail.net',
  'gishpuppy.com',
  'gmail.com.br', // typo-squatter
  'gmial.com', // typo-squatter
  'gnmail.com', // typo-squatter
  'godmail.gq',
  'grr.la',
  'gsrv.co.uk',
  'guerrillamail.biz',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.info',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'gustr.com',
  'h8s.org',
  'haltospam.com',
  'harakirimail.com',
  'hatespam.org',
  'herp.in',
  'hidemail.de',
  'hidzz.com',
  'hmamail.com',
  'hochsitze.com',
  'hopemail.biz',
  'humaility.com',
  'hurify1.com',
  'ieatspam.eu',
  'ieatspam.info',
  'ieh-mail.de',
  'ikbenspamvrij.nl',
  'imails.info',
  'inbax.tk',
  'inbox.si',
  'inboxalias.com',
  'incognitomail.com',
  'incognitomail.net',
  'incognitomail.org',
  'insorg-mail.info',
  'instant-mail.de',
  'ip6.li',
  'ispungebob.com',
  'jetable.com',
  'jetable.fr.nf',
  'jetable.net',
  'jetable.org',
  'jnxjn.com',
  'joliefile.net',
  'junk1.tk',
  'junkmail.ga',
  'junkmail.gq',
  'jupimail.com',
  'kasmail.com',
  'kaspop.com',
  'keepmymail.com',
  'killmail.com',
  'killmail.net',
  'kimsdisk.com',
  'klassmaster.com',
  'klassmaster.net',
  'koszmail.pl',
  'kulturbetrieb.info',
  'kurzepost.de',
  'l33r.eu',
  'laoeq.com',
  'lastmail.co',
  'lastmail.com',
  'letthemeatspam.com',
  'lhsdv.com',
  'lifebyfood.com',
  'link2mail.net',
  'litedrop.com',
  'loadby.us',
  'lol.ovpn.to',
  'lolfreak.net',
  'lookugly.com',
  'lopl.co.cc',
  'lortemail.dk',
  'lr78.com',
  'lroid.com',
  'lukop.dk',
  'm21.cc',
  'mail-filter.com',
  'mail-temporaire.com',
  'mail-temporaire.fr',
  'mail.mezimages.net',
  'mail.zp.ua',
  'mail1a.de',
  'mail21.cc',
  'mail2rss.org',
  'mail333.com',
  'mail4trash.com',
  'mailbidon.com',
  'mailbiz.biz',
  'mailblocks.com',
  'mailbucket.org',
  'mailc.net',
  'mailcat.biz',
  'mailcatch.com',
  'mailde.de',
  'mailde.info',
  'maildrop.cc',
  'maileater.com',
  'mailexpire.com',
  'mailf5.com',
  'mailfree.ga',
  'mailfreeonline.com',
  'mailfs.com',
  'mailguard.me',
  'mailhazard.com',
  'mailhazard.us',
  'mailimate.com',
  'mailinator.com',
  'mailinator.net',
  'mailinator.org',
  'mailinator2.com',
  'mailincubator.com',
  'mailismagic.com',
  'mailme.ir',
  'mailme.lv',
  'mailme24.com',
  'mailmetrash.com',
  'mailmoat.com',
  'mailnew.com',
  'mailnull.com',
  'mailpick.biz',
  'mailquack.com',
  'mailrock.biz',
  'mailscrap.com',
  'mailshell.com',
  'mailsiphon.com',
  'mailslapping.com',
  'mailslite.com',
  'mailtemp.info',
  'mailtemporal.com',
  'mailtemporaire.com',
  'mailtemporaire.fr',
  'mailtrash.net',
  'mailtv.net',
  'mailtv.tv',
  'mailzilla.com',
  'makemetheking.com',
  'manifestgenerator.com',
  'manybrain.com',
  'mbx.cc',
  'mega.zik.dj',
  'meinspamschutz.de',
  'meltmail.com',
  'messagebeamer.de',
  'messwiththebestdielikethe.rest',
  'mierdamail.com',
  'minex-coin.com',
  'minionmail.com',
  'mintmail.biz',
  'misterpinball.de',
  'mji.ro',
  'mmmmail.com',
  'moakt.co',
  'moakt.com',
  'moakt.ws',
  'mohmal.com',
  'motormania.cc',
  'mox.pp.ua',
  'mozej.com',
  'mpdmail.com',
  'msft.cloudns.cx',
  'mt2009.com',
  'mt2014.com',
  'mu.riseup.net',
  'mucincanin.com',
  'muhammadafandi.com',
  'mxp.dns-cloud.net',
  'mycard.net.ua',
  'mymail-in.net',
  'mypacks.net',
  'mypartyclip.de',
  'myphantomemail.com',
  'myspaceinc.com',
  'myspaceinc.net',
  'myspaceinc.org',
  'myspacepimpedup.com',
  'myspamless.com',
  'mytrashmail.com',
  'netzidiot.de',
  'neverbox.com',
  'nice-4u.com',
  'no-spam.ws',
  'noblepioneer.com',
  'noclickemail.com',
  'nogmailspam.info',
  'nospam.ze.tc',
  'nospam4.us',
  'nospamfor.us',
  'nospammail.net',
  'nospamthanks.info',
  'notmailinator.com',
  'notsharingmy.info',
  'nowmymail.com',
  'nullbox.info',
  'obobbo.com',
  'odaymail.com',
  'odnorazovoe.ru',
  'one-time.email',
  'oneoffemail.com',
  'onewaymail.com',
  'online.ms',
  'onqin.com',
  'oopi.org',
  'opayq.com',
  'ordinaryamerican.net',
  'owlpic.com',
  'p33.org',
  'paplayer.com',
  'payspun.com',
  'pepbot.com',
  'pjjkp.com',
  'plexolan.de',
  'poczta.onet.pl', // sometimes abused
  'politikerclub.de',
  'poofy.org',
  'pookmail.com',
  'pop3.xyz',
  'powered.name',
  'privy-mail.com',
  'prmail.top',
  'proxymail.eu',
  'prtnx.com',
  'prtz.eu',
  'pubmail886.com',
  'putthisinyourspamdatabase.com',
  'qq.com', // often abused for throwaway
  'queuemail.com',
  'quickinbox.com',
  'quickmail.nl',
  'rcpt.at',
  'reallymymail.com',
  'recursor.net',
  'recyclemail.dk',
  'regbypass.com',
  'regbypass.comsafe-mail.net',
  'rejectmail.com',
  'rklips.com',
  'rmqkr.net',
  'royal.net',
  'rppkn.com',
  'rtrtr.com',
  's0ny.net',
  'safe-mail.net',
  'safetymail.info',
  'safetypost.de',
  'sandelf.de',
  'saynotospams.com',
  'schafmail.de',
  'schrott-email.de',
  'secretemail.de',
  'secure-mail.biz',
  'selfdestructingmail.com',
  'senseless-entertainment.com',
  'sent.as',
  'sharedmailbox.org',
  'sharklasers.com',
  'shieldedmail.com',
  'shieldemail.com',
  'shiftmail.com',
  'shitmail.me',
  'shitware.nl',
  'shmeriously.com',
  'shortmail.net',
  'sibmail.com',
  'sinbox.net',
  'skeefmail.com',
  'slaskpost.se',
  'slopsbox.com',
  'slowslow.de',
  'smellfear.com',
  'snakemail.com',
  'sneakemail.com',
  'sneakmail.de',
  'snkmail.com',
  'sofimail.com',
  'sofort-mail.de',
  'sogetthis.com',
  'sohu.com', // sometimes abused
  'spam.la',
  'spam.mn',
  'spam.org.tr',
  'spam.su',
  'spam4.me',
  'spamail.de',
  'spamavert.com',
  'spambob.com',
  'spambob.net',
  'spambob.org',
  'spamcannon.com',
  'spamcannon.net',
  'spamcero.com',
  'spamcon.org',
  'spamcorptastic.com',
  'spamcowboy.com',
  'spamcowboy.net',
  'spamcowboy.org',
  'spamday.com',
  'spamex.com',
  'spamfree.eu',
  'spamfree24.com',
  'spamfree24.de',
  'spamfree24.eu',
  'spamfree24.info',
  'spamfree24.net',
  'spamfree24.org',
  'spamgob.com',
  'spamgoes.in',
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',
  'spamherelots.com',
  'spamherelots.net',
  'spamhereplease.com',
  'spamhereplease.net',
  'spamhole.com',
  'spamify.com',
  'spaminator.de',
  'spamkill.info',
  'spaml.com',
  'spaml.de',
  'spammotel.com',
  'spamoff.de',
  'spamsalad.in',
  'spamslicer.com',
  'spamspot.com',
  'spamstack.net',
  'spamthis.co.uk',
  'spamthisplease.com',
  'spamtrail.com',
  'spamtrap.ro',
  'spamty.eu',
  'spamwc.de',
  'spamwc.net',
  'spamwc.org',
  'speed.1s.fr',
  'speedymail.org',
  'spl0.com',
  'spnkr.me',
  'squizzy.de',
  'squizzy.eu',
  'squizzy.net',
  'sr.ro',
  'ssoia.com',
  'startfu.com',
  'startkeys.com',
  'stinkefinger.net',
  'stop-my-spam.com',
  'streetwisemail.com',
  'stuffmail.de',
  'subpaige.com',
  'super-auswahl.de',
  'supergreatmail.com',
  'supermailer.jp',
  'superrito.com',
  'superstachel.de',
  'suremail.info',
  'sweetxxx.de',
  'tafmail.com',
  'tagyourself.com',
  'teewars.org',
  'teleworm.com',
  'teleworm.us',
  'temp-mail.de',
  'temp-mail.io',
  'temp-mail.org',
  'temp-mail.ru',
  'temp.emeraldwebmail.com',
  'temp.headstrong.de',
  'tempail.com',
  'tempalias.com',
  'tempinbox.co.uk',
  'tempinbox.com',
  'tempmail.com',
  'tempmail.de',
  'tempmail.eu',
  'tempmail.it',
  'tempmail.net',
  'tempmail.org',
  'tempmail2.com',
  'tempmailer.com',
  'tempmailer.de',
  'tempomail.fr',
  'temporamail.com',
  'temporarioemail.com.br',
  'temporaryemail.net',
  'temporaryemail.us',
  'temporaryforwarding.com',
  'temporaryinbox.com',
  'temporarymailaddress.com',
  'tempsky.com',
  'tempthe.net',
  'tgasa.com',
  'thankyou2010.com',
  'thc.st',
  'thedoghousemail.com',
  'theinternetemail.com',
  'thespamhere.com',
  'thesunrisemail.com',
  'throwam.com',
  'throwaway.email',
  'throwam.com',
  'throwamailaway.com',
  'ti.junk.to',
  'tilapiamail.com',
  'tinoza.org',
  'tinyurl24.com',
  'tipsb.com',
  'tmailinator.com',
  'toiea.com',
  'tradermail.info',
  'trash-mail.at',
  'trash-mail.cf',
  'trash-mail.com',
  'trash-mail.de',
  'trash-mail.ga',
  'trash-mail.gq',
  'trash-mail.io',
  'trash-mail.ml',
  'trash-mail.net',
  'trash-mail.tk',
  'trash2009.com',
  'trash2010.com',
  'trash2011.com',
  'trashcan.dk',
  'trashdevil.com',
  'trashdevil.de',
  'trashemail.de',
  'trashinbox.com',
  'trashmail.at',
  'trashmail.com',
  'trashmail.de',
  'trashmail.io',
  'trashmail.me',
  'trashmail.net',
  'trashmail.org',
  'trashmail.xyz',
  'trashmailer.com',
  'trashme.in',
  'trashmycash.com',
  'trashspam.com',
  'trbvm.com',
  'trillianpro.com',
  'tryalert.com',
  'ttttt.dynu.net',
  'turual.com',
  'twinmail.de',
  'tyrex.net',
  'uggsrock.com',
  'umail.net',
  'upliftnow.com',
  'uplipht.com',
  'uroid.com',
  'us.af',
  'venompen.com',
  'veryrealemail.com',
  'viditag.com',
  'viewcastmedia.com',
  'viewcastmedia.net',
  'viewcastmedia.org',
  'viralplays.com',
  'vmail.me',
  'vomoto.com',
  'vpn.st',
  'vsimcard.com',
  'vubby.com',
  'walala.org',
  'walkmail.net',
  'webemail.me',
  'webm4il.info',
  'weg-werf-email.de',
  'wegwerf-emails.de',
  'wegwerfadresse.de',
  'wegwerfemail.de',
  'wegwerfemail.net',
  'wegwerfemail.org',
  'wegwerfmail.de',
  'wegwerfmail.info',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wegwerfmaildienst.de',
  'wh4f.org',
  'whyspam.me',
  'wickmail.net',
  'wilemail.com',
  'willhackforfood.biz',
  'willselfdestruct.com',
  'winemaven.info',
  'wronghead.com',
  'wuzupmail.net',
  'www.e4ward.com',
  'www.mailinator.com',
  'wwwnew.eu',
  'x.ip6.li',
  'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xmaily.com',
  'xoxy.net',
  'xsmail.com',
  'xzapmail.com',
  'ya.ru',
  'yanet.me',
  'yepmail.net',
  'yet.com',
  'yogamaven.com',
  'yomail.info',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'youmails.online',
  'ypmail.webarnak.fr.eu.org',
  'yuurok.com',
  'zehnminuten.de',
  'zehnminutenmail.de',
  'zhouemail.510520.org',
  'zilmail.com',
  'zippymail.info',
  'zomail.org',
  'zomg.info',
]);

// ─── Layer 2: Disposable domain check ───────────────────────────────────────
export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase().trim();
  if (!domain) return true; // malformed
  return DISPOSABLE_DOMAINS.has(domain);
}

// ─── Layer 3: MX Record DNS check ────────────────────────────────────────────
/**
 * Returns true when the domain has at least one MX record,
 * i.e. it is configured to receive email.
 * Caches results in a module-level Map to avoid redundant DNS queries.
 */
const mxCache = new Map<string, { result: boolean; ts: number }>();
const MX_CACHE_TTL_MS = 5 * 60 * 1000; // 5 minutes

export async function hasMxRecord(email: string): Promise<boolean> {
  const domain = email.split('@')[1]?.toLowerCase().trim();
  if (!domain) return false;

  // Cache hit
  const cached = mxCache.get(domain);
  if (cached && Date.now() - cached.ts < MX_CACHE_TTL_MS) {
    return cached.result;
  }

  try {
    const records = await dns.resolveMx(domain);
    const result = Array.isArray(records) && records.length > 0;
    mxCache.set(domain, { result, ts: Date.now() });
    return result;
  } catch {
    // ENOTFOUND, ENODATA, ENORECORD etc. → domain doesn't exist or has no MX
    mxCache.set(domain, { result: false, ts: Date.now() });
    return false;
  }
}

// ─── Combined validator ───────────────────────────────────────────────────────
export type EmailValidationResult =
  | { valid: true }
  | { valid: false; reason: 'disposable' | 'no_mx' | 'format' };

export async function validateSubscriberEmail(email: string): Promise<EmailValidationResult> {
  // Basic format check
  if (!email || !/^\S+@\S+\.\S+$/.test(email)) {
    return { valid: false, reason: 'format' };
  }

  // Layer 2: Disposable domain
  if (isDisposableEmail(email)) {
    return { valid: false, reason: 'disposable' };
  }

  // Layer 3: MX record — real mail server exists?
  const mx = await hasMxRecord(email);
  if (!mx) {
    return { valid: false, reason: 'no_mx' };
  }

  return { valid: true };
}

// ─── Human-readable error messages ───────────────────────────────────────────
export function emailValidationMessage(reason: 'disposable' | 'no_mx' | 'format'): string {
  switch (reason) {
    case 'disposable':
      return 'Temporary or disposable email addresses are not allowed. Please use a real email address.';
    case 'no_mx':
      return 'This email domain does not appear to be valid or does not accept emails. Please double-check your address.';
    case 'format':
      return 'Please provide a valid email address.';
  }
}
