export interface PresetSkill {
  id: string;
  name: string;
  category: 'languages' | 'frontend' | 'backend' | 'styling-ui' | 'database' | 'tools-devops';
  icon: string;
}

export const PRESET_SKILLS: PresetSkill[] = [
  // Top Popular / Modern Web Stack (First things users want to pick!)
  { id: 'react', name: 'React', category: 'frontend', icon: 'devicon-react-original colored' },
  { id: 'nextjs', name: 'Next.js', category: 'frontend', icon: 'devicon-nextjs-plain' },
  {
    id: 'typescript',
    name: 'TypeScript',
    category: 'languages',
    icon: 'devicon-typescript-plain colored',
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    category: 'languages',
    icon: 'devicon-javascript-plain colored',
  },
  { id: 'nodejs', name: 'Node.js', category: 'backend', icon: 'devicon-nodejs-plain colored' },
  {
    id: 'tailwindcss',
    name: 'Tailwind CSS',
    category: 'styling-ui',
    icon: 'devicon-tailwindcss-plain colored',
  },
  { id: 'python', name: 'Python', category: 'languages', icon: 'devicon-python-plain colored' },
  { id: 'express', name: 'Express', category: 'backend', icon: 'devicon-express-original' },
  { id: 'nestjs', name: 'NestJS', category: 'backend', icon: 'devicon-nestjs-original colored' },
  { id: 'mongodb', name: 'MongoDB', category: 'database', icon: 'devicon-mongodb-plain colored' },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'database',
    icon: 'devicon-postgresql-plain colored',
  },
  { id: 'docker', name: 'Docker', category: 'tools-devops', icon: 'devicon-docker-plain colored' },
  { id: 'git', name: 'Git', category: 'tools-devops', icon: 'devicon-git-plain colored' },
  {
    id: 'github',
    name: 'GitHub',
    category: 'tools-devops',
    icon: 'devicon-github-original colored',
  },
  { id: 'html5', name: 'HTML5', category: 'styling-ui', icon: 'devicon-html5-plain colored' },
  { id: 'css3', name: 'CSS3', category: 'styling-ui', icon: 'devicon-css3-plain colored' },
  { id: 'vuejs', name: 'Vue.js', category: 'frontend', icon: 'devicon-vuejs-plain colored' },
  { id: 'nuxtjs', name: 'Nuxt.js', category: 'frontend', icon: 'devicon-nuxtjs-plain colored' },
  { id: 'angular', name: 'Angular', category: 'frontend', icon: 'devicon-angular-plain colored' },
  { id: 'svelte', name: 'Svelte', category: 'frontend', icon: 'devicon-svelte-plain colored' },
  { id: 'redux', name: 'Redux', category: 'frontend', icon: 'devicon-redux-original colored' },
  { id: 'graphql', name: 'GraphQL', category: 'backend', icon: 'devicon-graphql-plain colored' },
  { id: 'prisma', name: 'Prisma', category: 'database', icon: 'devicon-prisma-original colored' },
  { id: 'redis', name: 'Redis', category: 'database', icon: 'devicon-redis-plain colored' },
  { id: 'mysql', name: 'MySQL', category: 'database', icon: 'devicon-mysql-plain colored' },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'database',
    icon: 'devicon-supabase-plain colored',
  },
  {
    id: 'firebase',
    name: 'Firebase',
    category: 'database',
    icon: 'devicon-firebase-plain colored',
  },
  {
    id: 'aws',
    name: 'AWS',
    category: 'tools-devops',
    icon: 'devicon-amazonwebservices-plain-wordmark colored',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'tools-devops',
    icon: 'devicon-vercel-original colored',
  },
  { id: 'linux', name: 'Linux', category: 'tools-devops', icon: 'devicon-linux-plain colored' },

  // Languages
  { id: 'go', name: 'Go', category: 'languages', icon: 'devicon-go-original-wordmark colored' },
  { id: 'rust', name: 'Rust', category: 'languages', icon: 'devicon-rust-original' },
  { id: 'java', name: 'Java', category: 'languages', icon: 'devicon-java-plain colored' },
  { id: 'php', name: 'PHP', category: 'languages', icon: 'devicon-php-plain colored' },
  { id: 'ruby', name: 'Ruby', category: 'languages', icon: 'devicon-ruby-plain colored' },
  { id: 'c', name: 'C', category: 'languages', icon: 'devicon-c-plain colored' },
  { id: 'cplusplus', name: 'C++', category: 'languages', icon: 'devicon-cplusplus-plain colored' },
  { id: 'csharp', name: 'C#', category: 'languages', icon: 'devicon-csharp-plain colored' },
  { id: 'swift', name: 'Swift', category: 'languages', icon: 'devicon-swift-plain colored' },
  { id: 'kotlin', name: 'Kotlin', category: 'languages', icon: 'devicon-kotlin-plain colored' },
  { id: 'dart', name: 'Dart', category: 'languages', icon: 'devicon-dart-plain colored' },
  { id: 'scala', name: 'Scala', category: 'languages', icon: 'devicon-scala-plain colored' },
  { id: 'elixir', name: 'Elixir', category: 'languages', icon: 'devicon-elixir-plain colored' },
  { id: 'bash', name: 'Bash', category: 'languages', icon: 'devicon-bash-plain colored' },
  {
    id: 'solidity',
    name: 'Solidity',
    category: 'languages',
    icon: 'devicon-solidity-plain colored',
  },
  { id: 'lua', name: 'Lua', category: 'languages', icon: 'devicon-lua-plain colored' },
  { id: 'r', name: 'R', category: 'languages', icon: 'devicon-r-plain colored' },
  { id: 'haskell', name: 'Haskell', category: 'languages', icon: 'devicon-haskell-plain colored' },
  { id: 'erlang', name: 'Erlang', category: 'languages', icon: 'devicon-erlang-plain colored' },
  { id: 'clojure', name: 'Clojure', category: 'languages', icon: 'devicon-clojure-plain colored' },
  { id: 'ocaml', name: 'OCaml', category: 'languages', icon: 'devicon-ocaml-plain colored' },
  { id: 'perl', name: 'Perl', category: 'languages', icon: 'devicon-perl-plain colored' },
  { id: 'zig', name: 'Zig', category: 'languages', icon: 'devicon-zig-original colored' },
  { id: 'nim', name: 'Nim', category: 'languages', icon: 'devicon-nim-plain colored' },
  { id: 'julia', name: 'Julia', category: 'languages', icon: 'devicon-julia-plain colored' },
  { id: 'matlab', name: 'MATLAB', category: 'languages', icon: 'devicon-matlab-plain colored' },
  {
    id: 'objectivec',
    name: 'Objective-C',
    category: 'languages',
    icon: 'devicon-objectivec-plain colored',
  },
  {
    id: 'crystal',
    name: 'Crystal',
    category: 'languages',
    icon: 'devicon-crystal-original colored',
  },
  { id: 'elm', name: 'Elm', category: 'languages', icon: 'devicon-elm-plain colored' },
  {
    id: 'purescript',
    name: 'PureScript',
    category: 'languages',
    icon: 'devicon-purescript-original colored',
  },
  { id: 'haxe', name: 'Haxe', category: 'languages', icon: 'devicon-haxe-plain colored' },
  { id: 'vuejs', name: 'Vue.js', category: 'frontend', icon: 'devicon-vuejs-plain colored' },
  { id: 'nuxtjs', name: 'Nuxt.js', category: 'frontend', icon: 'devicon-nuxtjs-plain colored' },
  { id: 'angular', name: 'Angular', category: 'frontend', icon: 'devicon-angular-plain colored' },
  {
    id: 'angularjs',
    name: 'AngularJS',
    category: 'frontend',
    icon: 'devicon-angularjs-plain colored',
  },
  { id: 'svelte', name: 'Svelte', category: 'frontend', icon: 'devicon-svelte-plain colored' },
  { id: 'astro', name: 'Astro', category: 'frontend', icon: 'devicon-astro-plain colored' },
  { id: 'gatsby', name: 'Gatsby', category: 'frontend', icon: 'devicon-gatsby-plain colored' },
  { id: 'remix', name: 'Remix', category: 'frontend', icon: 'devicon-remix-original colored' },
  { id: 'solidjs', name: 'Solid.js', category: 'frontend', icon: 'devicon-solidjs-plain colored' },
  { id: 'qwik', name: 'Qwik', category: 'frontend', icon: 'devicon-qwik-plain colored' },
  {
    id: 'alpinejs',
    name: 'Alpine.js',
    category: 'frontend',
    icon: 'devicon-alpinejs-plain colored',
  },
  {
    id: 'ember',
    name: 'Ember.js',
    category: 'frontend',
    icon: 'devicon-ember-original-wordmark colored',
  },
  {
    id: 'backbonejs',
    name: 'Backbone.js',
    category: 'frontend',
    icon: 'devicon-backbonejs-plain colored',
  },
  { id: 'meteor', name: 'Meteor.js', category: 'frontend', icon: 'devicon-meteor-plain colored' },
  { id: 'redux', name: 'Redux', category: 'frontend', icon: 'devicon-redux-original colored' },
  { id: 'jquery', name: 'jQuery', category: 'frontend', icon: 'devicon-jquery-plain colored' },
  {
    id: 'threejs',
    name: 'Three.js',
    category: 'frontend',
    icon: 'devicon-threejs-original colored',
  },
  { id: 'd3js', name: 'D3.js', category: 'frontend', icon: 'devicon-d3js-plain colored' },
  {
    id: 'socketio',
    name: 'Socket.io',
    category: 'frontend',
    icon: 'devicon-socketio-original colored',
  },
  {
    id: 'electron',
    name: 'Electron',
    category: 'frontend',
    icon: 'devicon-electron-original colored',
  },
  { id: 'tauri', name: 'Tauri', category: 'frontend', icon: 'devicon-tauri-plain colored' },

  // Styling & UI
  { id: 'html5', name: 'HTML5', category: 'styling-ui', icon: 'devicon-html5-plain colored' },
  { id: 'css3', name: 'CSS3', category: 'styling-ui', icon: 'devicon-css3-plain colored' },
  {
    id: 'tailwindcss',
    name: 'Tailwind CSS',
    category: 'styling-ui',
    icon: 'devicon-tailwindcss-plain colored',
  },
  { id: 'sass', name: 'Sass', category: 'styling-ui', icon: 'devicon-sass-original colored' },
  {
    id: 'bootstrap',
    name: 'Bootstrap',
    category: 'styling-ui',
    icon: 'devicon-bootstrap-plain colored',
  },
  {
    id: 'materialui',
    name: 'Material UI',
    category: 'styling-ui',
    icon: 'devicon-materialui-plain colored',
  },
  {
    id: 'antdesign',
    name: 'Ant Design',
    category: 'styling-ui',
    icon: 'devicon-antdesign-plain colored',
  },
  { id: 'bulma', name: 'Bulma', category: 'styling-ui', icon: 'devicon-bulma-plain colored' },
  {
    id: 'foundation',
    name: 'Foundation',
    category: 'styling-ui',
    icon: 'devicon-foundation-plain colored',
  },
  { id: 'stylus', name: 'Stylus', category: 'styling-ui', icon: 'devicon-stylus-plain colored' },
  {
    id: 'less',
    name: 'Less.js',
    category: 'styling-ui',
    icon: 'devicon-less-plain-wordmark colored',
  },
  { id: 'postcss', name: 'PostCSS', category: 'styling-ui', icon: 'devicon-postcss-plain colored' },
  { id: 'vuetify', name: 'Vuetify', category: 'styling-ui', icon: 'devicon-vuetify-line colored' },
  {
    id: 'storybook',
    name: 'Storybook',
    category: 'styling-ui',
    icon: 'devicon-storybook-plain colored',
  },

  // Build Tools & Bundlers
  { id: 'vite', name: 'Vite', category: 'tools-devops', icon: 'devicon-vitejs-plain colored' },
  {
    id: 'webpack',
    name: 'Webpack',
    category: 'tools-devops',
    icon: 'devicon-webpack-plain colored',
  },
  { id: 'babel', name: 'Babel', category: 'tools-devops', icon: 'devicon-babel-plain colored' },
  {
    id: 'rollup',
    name: 'Rollup.js',
    category: 'tools-devops',
    icon: 'devicon-rollup-plain colored',
  },
  { id: 'gulp', name: 'Gulp.js', category: 'tools-devops', icon: 'devicon-gulp-plain colored' },
  { id: 'grunt', name: 'Grunt.js', category: 'tools-devops', icon: 'devicon-grunt-plain colored' },
  {
    id: 'eslint',
    name: 'ESLint',
    category: 'tools-devops',
    icon: 'devicon-eslint-original colored',
  },
  {
    id: 'eleventy',
    name: 'Eleventy',
    category: 'tools-devops',
    icon: 'devicon-eleventy-plain colored',
  },
  { id: 'hugo', name: 'Hugo', category: 'tools-devops', icon: 'devicon-hugo-plain colored' },
  { id: 'jekyll', name: 'Jekyll', category: 'tools-devops', icon: 'devicon-jekyll-plain colored' },

  // Backend & APIs
  { id: 'nodejs', name: 'Node.js', category: 'backend', icon: 'devicon-nodejs-plain colored' },
  { id: 'express', name: 'Express', category: 'backend', icon: 'devicon-express-original' },
  { id: 'nestjs', name: 'NestJS', category: 'backend', icon: 'devicon-nestjs-original colored' },
  { id: 'fastify', name: 'Fastify', category: 'backend', icon: 'devicon-fastify-plain colored' },
  {
    id: 'adonisjs',
    name: 'AdonisJS',
    category: 'backend',
    icon: 'devicon-adonisjs-original colored',
  },
  {
    id: 'feathers',
    name: 'Feathers',
    category: 'backend',
    icon: 'devicon-feathersjs-original colored',
  },
  { id: 'django', name: 'Django', category: 'backend', icon: 'devicon-django-plain colored' },
  {
    id: 'djangorest',
    name: 'Django REST',
    category: 'backend',
    icon: 'devicon-djangorest-line colored',
  },
  { id: 'fastapi', name: 'FastAPI', category: 'backend', icon: 'devicon-fastapi-plain colored' },
  { id: 'flask', name: 'Flask', category: 'backend', icon: 'devicon-flask-original colored' },
  { id: 'laravel', name: 'Laravel', category: 'backend', icon: 'devicon-laravel-original colored' },
  { id: 'lumen', name: 'Lumen', category: 'backend', icon: 'devicon-lumen-original colored' },
  { id: 'symfony', name: 'Symfony', category: 'backend', icon: 'devicon-symfony-original colored' },
  { id: 'spring', name: 'Spring', category: 'backend', icon: 'devicon-spring-original colored' },
  { id: 'graphql', name: 'GraphQL', category: 'backend', icon: 'devicon-graphql-plain colored' },

  // Databases & Cloud & DevOps
  { id: 'mongodb', name: 'MongoDB', category: 'database', icon: 'devicon-mongodb-plain colored' },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'database',
    icon: 'devicon-postgresql-plain colored',
  },
  { id: 'mysql', name: 'MySQL', category: 'database', icon: 'devicon-mysql-plain colored' },
  { id: 'sqlite', name: 'SQLite', category: 'database', icon: 'devicon-sqlite-plain colored' },
  { id: 'redis', name: 'Redis', category: 'database', icon: 'devicon-redis-plain colored' },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'database',
    icon: 'devicon-supabase-plain colored',
  },
  {
    id: 'firebase',
    name: 'Firebase',
    category: 'database',
    icon: 'devicon-firebase-plain colored',
  },
  { id: 'prisma', name: 'Prisma', category: 'database', icon: 'devicon-prisma-original colored' },
  { id: 'docker', name: 'Docker', category: 'tools-devops', icon: 'devicon-docker-plain colored' },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    category: 'tools-devops',
    icon: 'devicon-kubernetes-plain colored',
  },
  { id: 'git', name: 'Git', category: 'tools-devops', icon: 'devicon-git-plain colored' },
  {
    id: 'github',
    name: 'GitHub',
    category: 'tools-devops',
    icon: 'devicon-github-original colored',
  },
  { id: 'gitlab', name: 'GitLab', category: 'tools-devops', icon: 'devicon-gitlab-plain colored' },
  { id: 'linux', name: 'Linux', category: 'tools-devops', icon: 'devicon-linux-plain colored' },
  { id: 'nginx', name: 'Nginx', category: 'tools-devops', icon: 'devicon-nginx-original colored' },
  {
    id: 'aws',
    name: 'AWS',
    category: 'tools-devops',
    icon: 'devicon-amazonwebservices-plain-wordmark colored',
  },
  {
    id: 'googlecloud',
    name: 'Google Cloud',
    category: 'tools-devops',
    icon: 'devicon-googlecloud-plain colored',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'tools-devops',
    icon: 'devicon-vercel-original colored',
  },
];
