export const siteConfig = {
  name: 'Md. Jasim',
  shortName: 'Jasim',
  role: 'Full Stack Developer & Senior Web Instructor',
  headline: 'Full Stack Developer | MERN & Next.js Specialist | Senior Instructor',
  bio: 'Full Stack Developer & Senior Web Instructor at Programming Hero. Specializing in high-performance web applications with React, Next.js, Node.js, TypeScript, and MongoDB. Mentored over 2,000+ developers.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://www.ismailjosim.com',
  resumeUrl: '/MD_JASIM_FullStack_Resume.pdf',
  ogImage: '/og-image.png',
  avatar: '/sticker.png',
  photo: '/person-vector.png',
  email: 'ismailjosim@yahoo.com',
  phone: '+880-1715-052-808',
  location: {
    city: 'Dhaka',
    country: 'Bangladesh',
    timezone: 'Asia/Dhaka',
    utcOffset: '+06:00',
  },
  socials: {
    github: 'https://github.com/ismailjosim',
    linkedin: 'https://www.linkedin.com/in/ismailjosim/',
    twitter: 'https://x.com/ismail_josim',
    facebook: 'https://www.facebook.com/ismailjosim99',
    whatsapp: 'https://wa.me/8801715052808',
  },
  organization: {
    name: 'Programming Hero',
    url: 'https://web.programming-hero.com/home',
    role: 'Senior Web Instructor',
  },
  skills: [
    'JavaScript',
    'TypeScript',
    'React',
    'Next.js',
    'Node.js',
    'Express.js',
    'MongoDB',
    'Mongoose',
    'Prisma',
    'Tailwind CSS',
    'Redux',
    'REST APIs',
    'WebSockets',
    'Docker',
    'Git',
    'Full Stack Web Development',
  ],
  keywords: [
    'Md. Jasim',
    'Ismail Josim',
    'ismailjosim',
    'Full Stack Developer',
    'Full Stack Engineer',
    'MERN Stack Developer',
    'Next.js Developer',
    'React Developer',
    'TypeScript Developer',
    'Node.js Developer',
    'Senior Web Instructor',
    'Programming Hero Instructor',
    'Web Developer Bangladesh',
    'Frontend Developer',
    'Backend Developer',
    'MongoDB Specialist',
    'Tailwind CSS v4',
    'Software Engineer Portfolio',
    'Web Development Mentor',
    'Full Stack SaaS Development',
  ],
};
